-- Audio, and the reason this template exists.
--
-- Sound is the one thing that behaves differently inside the Minit app than it
-- does in a browser, and it fails silently in both directions. Two facts drive
-- everything below.
--
-- 1. DEFOLD DISCARDS AUDIO WHILE ITS CONTEXT IS SUSPENDED. The web sound device
--    throws every buffer away and returns while the page's AudioContext is not
--    "running" -- no error, no retry. So a music loop started too early does not
--    queue up and play later: its opening is gone, and you hear the track from
--    wherever it had got to whenever the context finally wakes. That is why
--    music_start() below refuses until the context reports running, and the
--    caller retries.
--
-- 2. THE HOST OWNS THE OUTPUT GAIN. The app routes every game through a mute
--    gain it controls, seeded at zero. If its fade-up never lands, the game is
--    entirely healthy -- context running, engine mixing, buffers queued -- and
--    completely inaudible, with nothing observable from Lua. web/minit.html
--    carries the recovery for that; see the comments there.
--
-- Holding all playback until the run starts (set_active) is the third piece: it
-- puts every sound comfortably after the first tap, which is what actually
-- resumes the context.

local M = {}

local urls = {}
local enabled = true          -- the `sound` config value
local music_enabled = true    -- the `music` config value
local active = false          -- nothing plays before the game starts
local music_url = nil
local music_playing = false

-- Every clip generated by tools/gen-audio.mjs, plus the music loop.
local NAMES = { "tap", "bounce", "finish" }

-- Per-clip trim, so nothing has to be balanced at the call site.
local GAIN = { tap = 0.55, bounce = 0.5, finish = 0.8 }
local MUSIC_GAIN = 0.45

--- Resolve component urls. Call from a script on the game object that carries
--- the sound components.
function M.init()
    for _, name in ipairs(NAMES) do
        urls[name] = msg.url("#snd_" .. name)
    end
    music_url = msg.url("#music")
end

function M.configure(sound_on, music_on)
    enabled = sound_on
    music_enabled = music_on
end

--- Open the gate on all playback. Call when the game actually starts.
function M.set_active(on) active = on end

--- Is the page's audio context actually running?
--- Returns true off the web, and true when no context exists yet, so a caller
--- polling this can never deadlock.
function M.context_running()
    if not html5 then return true end
    local ok, res = pcall(html5.run,
        "(function(){var s=window._dmJSDeviceShared;var c=s&&s.audioCtx;" ..
        "return (!c||c.state==='running')?'1':'0';})()")
    return (not ok) or res ~= "0"
end

--- @param name string one of NAMES
--- @param opts table|nil { gain = number, speed = number }
function M.play(name, opts)
    if not enabled or not active then return end
    local url = urls[name]
    if not url then return end
    opts = opts or {}
    -- Defold accepts 0..50 for speed; clamp so a runaway caller cannot make a
    -- clip inaudible or turn it into a click.
    sound.play(url, {
        gain = (GAIN[name] or 0.7) * (opts.gain or 1),
        speed = math.max(0.5, math.min(2.0, opts.speed or 1)),
    })
end

--- Start the loop. Returns true once it is genuinely running, false while the
--- audio context is still asleep -- call it again next frame until it takes.
--- @return boolean
function M.music_start()
    if music_playing then return true end
    if not music_enabled then return true end     -- nothing to wait for
    if not M.context_running() then return false end
    music_playing = true
    go.set(music_url, "gain", MUSIC_GAIN)
    sound.play(music_url)
    return true
end

--- Fade out and stop. A result screen should not have a loop under it.
function M.music_stop(fade)
    if not music_playing then return end
    music_playing = false
    go.cancel_animations(music_url, "gain")
    go.animate(music_url, "gain", go.PLAYBACK_ONCE_FORWARD, 0,
               go.EASING_OUTQUAD, fade or 0.5, 0,
               function() sound.stop(music_url) end)
end

return M
